CREATE TABLE "inst" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "address" varchar,
  "active" bool DEFAULT 'true',
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "teacher" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "inst_id" integer,
  "name" varchar NOT NULL,
  "address" varchar,
  "status" bool DEFAULT 'true',
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "class" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "teacher_id" integer,
  "name" varchar,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "student" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" integer,
  "name" varchar NOT NULL,
  "address" varchar,
  "status" bool DEFAULT 'true',
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "assignment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" integer,
  "name" varchar NOT NULL,
  "status" bool DEFAULT 'true',
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "work" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" integer,
  "assignment_id" integer,
  "name" varchar NOT NULL,
  "status" bool DEFAULT 'true',
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "grade" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "work_id" integer,
  "name" varchar NOT NULL,
  "status" bool DEFAULT 'true',
  "created_at" timestamp DEFAULT 'now()'
);

ALTER TABLE "teacher" ADD FOREIGN KEY ("inst_id") REFERENCES "inst" ("id");

ALTER TABLE "class" ADD FOREIGN KEY ("teacher_id") REFERENCES "teacher" ("id");

ALTER TABLE "student" ADD FOREIGN KEY ("class_id") REFERENCES "class" ("id");

ALTER TABLE "assignment" ADD FOREIGN KEY ("class_id") REFERENCES "class" ("id");

ALTER TABLE "work" ADD FOREIGN KEY ("student_id") REFERENCES "student" ("id");

ALTER TABLE "work" ADD FOREIGN KEY ("assignment_id") REFERENCES "assignment" ("id");

ALTER TABLE "grade" ADD FOREIGN KEY ("work_id") REFERENCES "work" ("id");
